project:
  type: book

book:
  title: "Pins: Three Ways"
  author: "Ian Lyttle"
  date: "8/4/2022"
  chapters:
    - index.qmd
    #- using-r.qmd
    #- using-python.qmd
    - using-javascript.qmd

date: today
date-format: "YYYY-MM-DD"

engine: knitr

resources:
  - pins

format:
  html:
    theme: cosmo



